#!/bin/bash
# v1.0 bgp-filter
#
# Prints to default out bgp fields data
#
# Copyright 2017 Wladimir Guerra

USAGE_MESSAGE="
USAGE:
	
	$(basename $0) -s [separator] -q [d|s|n] -f [filter] [pcap-file]

OPTIONS:

-s [separator]
	The data separator. Must be a valid character. For further 
	details see tshark(1) -E separator option. The default is /t.

-q [d|s|n]
	Set quote character to surround fields. See tshark(1) -E 
	quote option for further details.

-f [filter]
	tshark filter.
"

SEPARATOR=/t
QUOTE=n
filter='ip.src==192.168.0.2&&!icmp&&skype.som.type!=0x2'

while getopts ":s:q:f:" opt
do
	case $opt in
		s)
			SEPARATOR=$OPTARG
		;;
		q)
			QUOTE=$OPTARG
		;;
		f)
			filter="$OPTARG"
		;;
	esac
done

# Shifts to the last argument
shift $((OPTIND -1))

pcap_file="$1"

if [ -z $pcap_file ]; then
	echo "$USAGE_MESSAGE"
	exit 1
fi

if [ ! -f $pcap_file ]; then
	echo "[$pcap_file] is an invalid file." >&2
	exit 1
fi

fields="\
-e _ws.col.Time \
-e frame.time_epoch \
-e frame.number \
-e ip.id
"

tshark -T fields -E separator=$SEPARATOR -E quote=$QUOTE $fields -r $pcap_file  $filter
