#!/bin/bash
# v1.0 bgp-filter
#
# Prints to default out bgp fields data
#
# Copyright 2017 Wladimir Guerra

USAGE_MESSAGE="
USAGE:

$(basename $0) -s [separator] -q [d|s|n] [pcap-file]

OPTIONS:

-s [separator]
	The data separator. Must be a valid character. 
	For further details see tshark(1) -E separator option. 
	The default is /t.

-q [d|s|n]
	Set quote character to surround fields. See tshark(1) 
	'-E quote' option for further details.

-f [filter]
	Filter to apply. See tshark(1) for further details. 
	Defaults to 'ospf.msg==4||ospf.msg==5'.

"

SEPARATOR=/t
QUOTE=n
FILTER="ospf.msg==4"

while getopts ":s:q:f:" opt
do
	case $opt in
		s)
			SEPARATOR=$OPTARG
		;;
		q)
			QUOTE=$OPTARG
		;;
		f)
			FILTER=$OPTARG
		;;
	esac
done

# Shifts to the last argument
shift $((OPTIND -1))

if [ -z $1 ]; then
	echo -e $USAGE_MESSAGE
	exit 1
fi

if [ ! -f $1 ]; then
	echo "[$1] is an invalid file." >&2
	exit 1
fi

fields="\
-e _ws.col.Time \
-e frame.time_relative \
-e ip.src \
-e ip.dst \
-e ospf.lsa \
-e ospf.advrouter \
-e ospf.lsa.router.linktype \
-e ospf.lsa.router.metric0 \
-e ospf.lsa.id"

tshark -T fields -E separator=$SEPARATOR -E quote=$QUOTE $fields -r $1 $FILTER
