#!/bin/sh

result_path="/hostlab/_test/results"
iperf_report_path="$result_path/iperf"
dump_path="$result_path/tcpdump"
index="$(pcap-file-index $dump_path)"
iperf_file_det=""

interval=1

USAGE_MESSAGE="
Usage:
	$(basename $0) -d [description] -i [seconds] 

Options:
	-d [description]
		Append [description] to the end of report filename.
	-i [seconds]
		Report interval default to 30s. See iperf man page -i option for further details.
	-h
		Print this help
"

while getopts ":d:i" opt
do
	case $opt in
		d)
			iperf_file_det="${OPTARG}-"
		;;
		i)
			interval="$OPTARG"
		;;
		*)
			echo "$USAGE_MESSAGE"
			exit 1
		;;
	esac
done

#shift $((OPTIND - 1))

# Incluir interface de teste como parametro -c comentário
iperf_srv_file="$iperf_report_path/${iperf_file_det}iperf-${index}-$(hostname)-srv.log"

iperf -s -u -i "$interval" > "$iperf_srv_file"
