#!/bin/bash
#
# v1.0 monitor
#
# Copyright 2017 Wladimir Guerra

USAGE_MESSAGE="
USAGE:
	$(basename $0) [protocol] [pcap-file]

Protocol can be bgp, rip or ospf.
" 

if [ -z $1 ]; then
	echo "$USAGE_MESSAGE"
	exit 1
fi

# To allow terminal title change
export PS1="\u@\h: \w\a${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\W\[\033[00m\]\$"

# Terminal Title
echo -en "\033]0;Filtro $1 em $2\a"

watch ./filter-$1 $2 
